
const OPEN_PARENTHESIS = "(";
const CLOSING_PARENTHESIS = ")";
const OR = "|";
const POSITIVE_CLOSURE = "+";
const KLEEN_CLOSURE = "*";
const CONCAT = ".";
const ZERO_OR_ONE = "?"
const EPSILON = "ε";
const OPERATORS = [OPEN_PARENTHESIS, CLOSING_PARENTHESIS, OR, POSITIVE_CLOSURE, KLEEN_CLOSURE, CONCAT, ZERO_OR_ONE];

export const constants = {
  OPEN_PARENTHESIS,
  CLOSING_PARENTHESIS,
  OR,
  POSITIVE_CLOSURE,
  KLEEN_CLOSURE,
  CONCAT,
  ZERO_OR_ONE,
  EPSILON,
  OPERATORS,
}